# Generated by Django 4.2.5 on 2023-09-06 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('TimeSheetId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('totalTime', models.IntegerField(blank=True, default=0, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('LineItemtId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField()),
                ('TimeSheetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.timesheet')),
            ],
        ),
    ]
