# Generated by Django 4.2.5 on 2023-09-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_timesheetid_lineitem_timesheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
