# Generated by Django 4.2.5 on 2023-09-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_lineitemid_lineitem_lineitemid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='timeSheetId',
            new_name='timesheetId',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='timeSheetId',
            new_name='timesheetId',
        ),
    ]
