# Generated by Django 4.2.5 on 2023-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_timesheetid_lineitem_timesheetid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
